# Generated by Django 5.0.2 on 2024-02-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
