# Generated by Django 5.0.2 on 2024-02-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_project_abstract_alter_project_support_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
