# Generated by Django 5.0.2 on 2024-02-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_mentor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
    ]
