# Generated by Django 5.0.2 on 2024-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_mentor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
