# Generated by Django 5.0.2 on 2024-02-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_alter_timeline_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(default='Pccoe', max_length=200),
            preserve_default=False,
        ),
    ]
