# Generated by Django 5.0.2 on 2024-02-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_alter_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
