# Generated by Django 5.0.2 on 2024-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_remove_timeline_admission_yr_timeline_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('InProgress', 'In Progress'), ('Submitted', 'Submitted')], default='Pending', max_length=20),
        ),
    ]
