# Generated by Django 5.0.2 on 2024-02-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_alter_projecttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='college',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='college.college'),
            preserve_default=False,
        ),
    ]
